#!/usr/bin/env node
/* eslint-disable no-console */
/**
 * LBTA mobile UX audit — Playwright screenshot sweep harness.
 *
 * Scope: read-only. Captures full-page PNG screenshots of audited pages at
 * the 7 breakpoints listed in .cursorrules Part 6. Writes to
 * docs/audits/2026-05/screenshots/{page-slug}-{breakpoint}.png.
 *
 * Usage (default — local dev server at http://localhost:3000):
 *   node scripts/audit/screenshot-sweep.mjs
 *
 * Override base URL:
 *   AUDIT_BASE_URL=http://localhost:4000 node scripts/audit/screenshot-sweep.mjs
 *   AUDIT_BASE_URL=https://lagunabeachtennisacademy.com node scripts/audit/screenshot-sweep.mjs
 *
 * Limit to a subset of pages:
 *   AUDIT_PAGES="/,/schedules,/book" node scripts/audit/screenshot-sweep.mjs
 *
 * Limit breakpoints:
 *   AUDIT_BREAKPOINTS="320,375,768" node scripts/audit/screenshot-sweep.mjs
 *
 * Notes:
 * - Idempotent: re-running overwrites screenshots in place.
 * - NOT wired into CI or package.json scripts (per plan scope guard).
 * - Output PNG (not WebP) so the file is openable in any preview without
 *   transcoding; the audit doc references these directly.
 */

import { chromium } from 'playwright'
import { mkdir, writeFile } from 'node:fs/promises'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)
const REPO_ROOT = path.resolve(__dirname, '..', '..')

const BASE_URL = process.env.AUDIT_BASE_URL || 'http://localhost:3000'

const DEFAULT_BREAKPOINTS = [320, 375, 390, 414, 768, 1024, 1440]
const DEFAULT_PAGES = [
  '/',
  '/schedules',
  '/book',
  '/junior-trial',
  '/adult-trial',
  '/programs',
  '/programs/junior',
  '/programs/adult',
  '/coaches',
  '/coaches/andrew-mateljan',
  '/about',
  '/contact',
  '/pathway-planner',
  '/thank-you',
]

const BREAKPOINTS = (process.env.AUDIT_BREAKPOINTS || '')
  .split(',')
  .map((s) => Number(s.trim()))
  .filter((n) => Number.isFinite(n) && n > 0)

const PAGES_OVERRIDE = (process.env.AUDIT_PAGES || '')
  .split(',')
  .map((s) => s.trim())
  .filter(Boolean)

const breakpoints = BREAKPOINTS.length > 0 ? BREAKPOINTS : DEFAULT_BREAKPOINTS
const pages = PAGES_OVERRIDE.length > 0 ? PAGES_OVERRIDE : DEFAULT_PAGES

const SCREENSHOTS_DIR = path.join(REPO_ROOT, 'docs', 'audits', '2026-05', 'screenshots')
const HEIGHT_FOR_VP = 900 // initial viewport height; full-page screenshot expands beyond this

function slugify(routePath) {
  if (routePath === '/' || routePath === '') return 'home'
  return routePath
    .replace(/^\//, '')
    .replace(/\/$/, '')
    .replace(/\//g, '--')
}

async function ensureDir(dir) {
  await mkdir(dir, { recursive: true })
}

async function captureOnce({ browser, route, breakpoint }) {
  const url = `${BASE_URL}${route}`
  const slug = slugify(route)
  const filePath = path.join(SCREENSHOTS_DIR, `${slug}-${breakpoint}.png`)

  const context = await browser.newContext({
    viewport: { width: breakpoint, height: HEIGHT_FOR_VP },
    deviceScaleFactor: 2,
    userAgent:
      breakpoint <= 414
        ? 'Mozilla/5.0 (iPhone; CPU iPhone OS 17_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.0 Mobile/15E148 Safari/604.1'
        : undefined,
    hasTouch: breakpoint <= 768,
    isMobile: breakpoint <= 768,
    reducedMotion: 'no-preference',
  })

  // Block GHL chat widget script so floating launcher doesn't obscure screenshots.
  // Audit observations about chat stacking come from a separate dedicated capture.
  await context.route(/widget\.leadconnectorhq\.com|app\.gohighlevel\.com|services\.leadconnectorhq\.com/, (r) => r.abort())

  const page = await context.newPage()
  try {
    const resp = await page.goto(url, { waitUntil: 'networkidle', timeout: 30000 })
    if (!resp || !resp.ok()) {
      console.warn(`  ! ${route} @ ${breakpoint}px — HTTP ${resp ? resp.status() : 'no response'}`)
    }
    // Give Framer Motion entrance + lazy images a beat.
    await page.waitForTimeout(800)
    await page.screenshot({ path: filePath, fullPage: true })
    console.log(`  ✓ ${slug}-${breakpoint}.png`)
  } catch (err) {
    console.warn(`  ! ${route} @ ${breakpoint}px — ${err.message}`)
    try {
      await page.screenshot({ path: filePath, fullPage: true }).catch(() => {})
    } catch {}
  } finally {
    await context.close()
  }
}

async function main() {
  console.log(`\nLBTA mobile UX audit — screenshot sweep`)
  console.log(`  base url:     ${BASE_URL}`)
  console.log(`  pages:        ${pages.length}`)
  console.log(`  breakpoints:  ${breakpoints.join(', ')}`)
  console.log(`  out dir:      ${SCREENSHOTS_DIR}\n`)

  await ensureDir(SCREENSHOTS_DIR)
  await writeFile(
    path.join(SCREENSHOTS_DIR, 'README.md'),
    `# Screenshots\n\nGenerated by \`scripts/audit/screenshot-sweep.mjs\`.\n\nNaming: \`{slug}-{breakpoint}.png\` (slug = route with \`/\` → \`--\`, root = \`home\`).\n\nGenerated against \`${BASE_URL}\`.\n`,
  )

  const browser = await chromium.launch({ headless: true })
  try {
    for (const route of pages) {
      console.log(`# ${route}`)
      for (const bp of breakpoints) {
        await captureOnce({ browser, route, breakpoint: bp })
      }
    }
  } finally {
    await browser.close()
  }

  console.log(`\ndone. ${pages.length} pages × ${breakpoints.length} breakpoints = ${pages.length * breakpoints.length} screenshots.`)
}

main().catch((err) => {
  console.error('Sweep failed:', err)
  process.exit(1)
})
