/**
 * Auto-generated by scripts/build-tokens.ts. Do not edit directly.
 *
 * Use these typed constants in TS logic that needs raw hex values
 * (e.g. computed accent colors, canvas/SVG drawing, chart libraries).
 * For className-based styling, prefer Tailwind classes (e.g. `bg-brand-deep-water`)
 * or CSS variables (e.g. `var(--brand-deep-water)`).
 *
 * Source of truth: tokens/lbta-web-tokens.json
 */

export const BRAND = {
  pacificDusk: '#1B3A5C',
  deepWater: '#0F2237',
  deepCard: '#0A1628',
  victoriaCove: '#2E8B8B',
  thousandSteps: '#C4963C',
  sunsetCliff: '#E8834A',
  sandstone: '#F5F0E5',
  morningLight: '#FAF8F4',
  saltAir: '#FFFFFF',
  tidePool: '#3A8B6E',
  sageHill: '#7A8B6E',
  driftwood: '#B8A88A',
} as const

export type BrandToken = keyof typeof BRAND
export type BrandValue = (typeof BRAND)[BrandToken]

/** Legacy lbta.* palette. Prefer BRAND for new code. */
export const LBTA = {
  burnt: '#E8834A',
  orange: '#E8834A',
  red: '#F04E23',
  beige: '#F5F0E5',
  black: '#0A0A0A',
  white: '#FFFFFF',
  cream: '#FAF8F4',
  sand: '#F5F0E5',
  stone: '#E8E4DF',
  charcoal: '#1B3A5C',
  slate: '#6B6B6B',
  primary: '#1B3A5C',
  secondary: '#6B6B6B',
  coral: '#E8834A',
  coralDark: '#D4773F',
  bone: '#FAF8F4',
} as const
