/**
 * Auto-generated by scripts/build-tokens.ts. Do not edit directly.
 *
 * Use these typed constants in TS logic that needs raw hex values
 * (e.g. computed accent colors, canvas/SVG drawing, chart libraries).
 * For className-based styling, prefer Tailwind classes (e.g. `bg-brand-deep-water`)
 * or CSS variables (e.g. `var(--brand-deep-water)`).
 *
 * Source of truth: tokens/lbta-web-tokens.json
 */

export const BRAND = {
  pacificDusk: '#1B3A5C',
  deepWater: '#0F2237',
  deepCard: '#0A1628',
  victoriaCove: '#2E8B8B',
  thousandSteps: '#C4963C',
  sunsetCliff: '#E8834A',
  sandstone: '#F5F0E5',
  morningLight: '#FAF8F4',
  saltAir: '#FFFFFF',
  tidePool: '#3A8B6E',
  sageHill: '#7A8B6E',
  driftwood: '#B8A88A',
} as const

export type BrandToken = keyof typeof BRAND
export type BrandValue = (typeof BRAND)[BrandToken]

/** Legacy lbta.* palette. Prefer BRAND for new code. */
export const LBTA = {
  burnt: '#E8834A',
  orange: '#E8834A',
  red: '#F04E23',
  beige: '#F5F0E5',
  black: '#0A0A0A',
  white: '#FFFFFF',
  cream: '#FAF8F4',
  sand: '#F5F0E5',
  stone: '#E8E4DF',
  charcoal: '#1B3A5C',
  slate: '#6B6B6B',
  primary: '#1B3A5C',
  secondary: '#6B6B6B',
  coral: '#E8834A',
  coralDark: '#D4773F',
  bone: '#FAF8F4',
} as const

/**
 * Look up a brand hex by its kebab-case token name
 * (matches the CSS variable suffix and Tailwind class).
 *
 * @example brandHex('pacific-dusk') // '#1B3A5C'
 */
export function brandHex(token: string): string | undefined {
  return BRAND_BY_KEBAB[token]
}

const BRAND_BY_KEBAB: Record<string, string> = {
  'pacific-dusk': '#1B3A5C',
  'deep-water': '#0F2237',
  'deep-card': '#0A1628',
  'victoria-cove': '#2E8B8B',
  'thousand-steps': '#C4963C',
  'sunset-cliff': '#E8834A',
  'sandstone': '#F5F0E5',
  'morning-light': '#FAF8F4',
  'salt-air': '#FFFFFF',
  'tide-pool': '#3A8B6E',
  'sage-hill': '#7A8B6E',
  'driftwood': '#B8A88A',
}
