import { mkdir, readFile, writeFile } from 'node:fs/promises'
import path from 'node:path'

type TokenFile = {
  colors: {
    brand: Record<string, string>
    lbta: Record<string, string>
  }
}

const repoRoot = process.cwd()
const tokenFilePath = path.join(repoRoot, 'tokens', 'lbta-web-tokens.json')
const generatedDir = path.join(repoRoot, 'generated')
const libDir = path.join(repoRoot, 'lib')
const tailwindOutputPath = path.join(generatedDir, 'tokens.tailwind.json')
const cssOutputPath = path.join(generatedDir, 'tokens.css')
const tsOutputPath = path.join(libDir, 'brand-tokens.ts')

function buildCssVariables(tokens: TokenFile): string {
  const lines: string[] = []

  lines.push('/* Auto-generated by scripts/build-tokens.ts. Do not edit directly. */')
  lines.push(':root {')

  for (const [token, value] of Object.entries(tokens.colors.brand)) {
    lines.push(`  --brand-${token}: ${value};`)
  }

  for (const [token, value] of Object.entries(tokens.colors.lbta)) {
    lines.push(`  --lbta-${token}: ${value};`)
  }

  lines.push('}')
  lines.push('')

  return `${lines.join('\n')}\n`
}

function kebabToCamel(input: string): string {
  return input.replace(/-([a-z0-9])/g, (_, ch: string) => ch.toUpperCase())
}

function buildTypedTokens(tokens: TokenFile): string {
  const lines: string[] = []
  lines.push('/**')
  lines.push(' * Auto-generated by scripts/build-tokens.ts. Do not edit directly.')
  lines.push(' *')
  lines.push(' * Use these typed constants in TS logic that needs raw hex values')
  lines.push(' * (e.g. computed accent colors, canvas/SVG drawing, chart libraries).')
  lines.push(' * For className-based styling, prefer Tailwind classes (e.g. `bg-brand-deep-water`)')
  lines.push(' * or CSS variables (e.g. `var(--brand-deep-water)`).')
  lines.push(' *')
  lines.push(' * Source of truth: tokens/lbta-web-tokens.json')
  lines.push(' */')
  lines.push('')

  // BRAND object (camelCase keys)
  lines.push('export const BRAND = {')
  for (const [token, value] of Object.entries(tokens.colors.brand)) {
    lines.push(`  ${kebabToCamel(token)}: '${value}',`)
  }
  lines.push('} as const')
  lines.push('')
  lines.push('export type BrandToken = keyof typeof BRAND')
  lines.push('export type BrandValue = (typeof BRAND)[BrandToken]')
  lines.push('')

  // LBTA legacy (kept for backwards compat)
  lines.push('/** Legacy lbta.* palette. Prefer BRAND for new code. */')
  lines.push('export const LBTA = {')
  for (const [token, value] of Object.entries(tokens.colors.lbta)) {
    lines.push(`  ${kebabToCamel(token)}: '${value}',`)
  }
  lines.push('} as const')
  lines.push('')

  return lines.join('\n')
}

async function main() {
  const raw = await readFile(tokenFilePath, 'utf8')
  const parsed = JSON.parse(raw) as TokenFile

  const tailwindPayload = {
    brand: parsed.colors.brand,
    lbta: parsed.colors.lbta,
  }

  const tailwindJson = `${JSON.stringify(tailwindPayload, null, 2)}\n`
  const cssVars = buildCssVariables(parsed)
  const typedTs = buildTypedTokens(parsed)

  await mkdir(generatedDir, { recursive: true })
  await mkdir(libDir, { recursive: true })
  await writeFile(tailwindOutputPath, tailwindJson, 'utf8')
  await writeFile(cssOutputPath, cssVars, 'utf8')
  await writeFile(tsOutputPath, typedTs, 'utf8')

  console.log(`Generated ${path.relative(repoRoot, tailwindOutputPath)}`)
  console.log(`Generated ${path.relative(repoRoot, cssOutputPath)}`)
  console.log(`Generated ${path.relative(repoRoot, tsOutputPath)}`)
}

main().catch((error) => {
  console.error('Failed to build tokens.')
  console.error(error)
  process.exitCode = 1
})
