import { mkdir, readFile, writeFile } from 'node:fs/promises'
import path from 'node:path'

type TokenFile = {
  colors: {
    brand: Record<string, string>
    lbta: Record<string, string>
  }
}

const repoRoot = process.cwd()
const tokenFilePath = path.join(repoRoot, 'tokens', 'lbta-web-tokens.json')
const generatedDir = path.join(repoRoot, 'generated')
const tailwindOutputPath = path.join(generatedDir, 'tokens.tailwind.json')
const cssOutputPath = path.join(generatedDir, 'tokens.css')

function buildCssVariables(tokens: TokenFile): string {
  const lines: string[] = []

  lines.push('/* Auto-generated by scripts/build-tokens.ts. Do not edit directly. */')
  lines.push(':root {')

  for (const [token, value] of Object.entries(tokens.colors.brand)) {
    lines.push(`  --brand-${token}: ${value};`)
  }

  for (const [token, value] of Object.entries(tokens.colors.lbta)) {
    lines.push(`  --lbta-${token}: ${value};`)
  }

  lines.push('}')
  lines.push('')

  return `${lines.join('\n')}\n`
}

async function main() {
  const raw = await readFile(tokenFilePath, 'utf8')
  const parsed = JSON.parse(raw) as TokenFile

  const tailwindPayload = {
    brand: parsed.colors.brand,
    lbta: parsed.colors.lbta,
  }

  const tailwindJson = `${JSON.stringify(tailwindPayload, null, 2)}\n`
  const cssVars = buildCssVariables(parsed)

  await mkdir(generatedDir, { recursive: true })
  await writeFile(tailwindOutputPath, tailwindJson, 'utf8')
  await writeFile(cssOutputPath, cssVars, 'utf8')

  console.log(`Generated ${path.relative(repoRoot, tailwindOutputPath)}`)
  console.log(`Generated ${path.relative(repoRoot, cssOutputPath)}`)
}

main().catch((error) => {
  console.error('Failed to build tokens.')
  console.error(error)
  process.exitCode = 1
})
