import { mkdir, readFile, writeFile } from 'node:fs/promises'
import path from 'node:path'

type TokenFile = {
  meta?: { name?: string; version?: string; updated?: string }
  colors: {
    brand: Record<string, string>
    lbta: Record<string, string>
  }
  lbtaUtility?: {
    allowed: string[]
    rationale?: Record<string, string>
  }
  deprecations?: Record<string, string>
}

const repoRoot = process.cwd()
const tokenFilePath = path.join(repoRoot, 'tokens', 'lbta-web-tokens.json')
const generatedDir = path.join(repoRoot, 'generated')
const libDir = path.join(repoRoot, 'lib')
const tailwindOutputPath = path.join(generatedDir, 'tokens.tailwind.json')
const cssOutputPath = path.join(generatedDir, 'tokens.css')
const tsOutputPath = path.join(libDir, 'brand-tokens.ts')

function buildCssVariables(tokens: TokenFile): string {
  const lines: string[] = []

  lines.push('/* Auto-generated by scripts/build-tokens.ts. Do not edit directly. */')
  lines.push(':root {')

  for (const [token, value] of Object.entries(tokens.colors.brand)) {
    lines.push(`  --brand-${token}: ${value};`)
  }

  for (const [token, value] of Object.entries(tokens.colors.lbta)) {
    lines.push(`  --lbta-${token}: ${value};`)
  }

  lines.push('}')
  lines.push('')

  return `${lines.join('\n')}\n`
}

function kebabToCamel(input: string): string {
  return input.replace(/-([a-z0-9])/g, (_, ch: string) => ch.toUpperCase())
}

function buildTypedTokens(tokens: TokenFile): string {
  const lines: string[] = []
  const allowedSet = new Set(tokens.lbtaUtility?.allowed ?? [])
  const utilityNames = Object.keys(tokens.colors.lbta).filter((k) => allowedSet.has(k))
  const legacyNames = Object.keys(tokens.colors.lbta).filter((k) => !allowedSet.has(k))

  lines.push('/**')
  lines.push(' * Auto-generated by scripts/build-tokens.ts. Do not edit directly.')
  lines.push(' *')
  lines.push(' * Use these typed constants in TS logic that needs raw hex values')
  lines.push(' * (e.g. computed accent colors, canvas/SVG drawing, chart libraries).')
  lines.push(' * For className-based styling, prefer Tailwind classes (e.g. `bg-brand-deep-water`)')
  lines.push(' * or CSS variables (e.g. `var(--brand-deep-water)`).')
  lines.push(' *')
  lines.push(' * Source of truth: tokens/lbta-web-tokens.json')
  lines.push(' */')
  lines.push('')

  // BRAND object — the 12 brand identity colors
  lines.push('/** Brand identity colors. Use these for everything brand-related. */')
  lines.push('export const BRAND = {')
  for (const [token, value] of Object.entries(tokens.colors.brand)) {
    lines.push(`  ${kebabToCamel(token)}: '${value}',`)
  }
  lines.push('} as const')
  lines.push('')
  lines.push('export type BrandToken = keyof typeof BRAND')
  lines.push('export type BrandValue = (typeof BRAND)[BrandToken]')
  lines.push('')

  // LBTA_UTIL — the 4 allowed utility colors (semantic, non-brand)
  if (utilityNames.length > 0) {
    lines.push('/**')
    lines.push(' * System utility colors — semantic roles the brand palette doesn\'t address.')
    lines.push(' * These are NOT brand colors. They fill specific functional needs.')
    lines.push(' *')
    if (tokens.lbtaUtility?.rationale) {
      for (const name of utilityNames) {
        const r = tokens.lbtaUtility.rationale[name]
        if (r) lines.push(` * - ${kebabToCamel(name)}: ${r}`)
      }
    }
    lines.push(' */')
    lines.push('export const LBTA_UTIL = {')
    for (const name of utilityNames) {
      lines.push(`  ${kebabToCamel(name)}: '${tokens.colors.lbta[name]}',`)
    }
    lines.push('} as const')
    lines.push('')
    lines.push('export type LbtaUtilToken = keyof typeof LBTA_UTIL')
    lines.push('')
  }

  // LBTA_LEGACY — deprecated names with @deprecated JSDoc per key
  if (legacyNames.length > 0) {
    lines.push('/**')
    lines.push(' * Legacy lbta-* color exports. ALL DEPRECATED.')
    lines.push(' *')
    lines.push(' * Editor tooling should surface @deprecated warnings on each key.')
    lines.push(' * Prefer BRAND.* (identity) or LBTA_UTIL.* (utility).')
    lines.push(' * See `tokens/lbta-web-tokens.json` `deprecations` map for replacement guidance.')
    lines.push(' */')
    lines.push('export const LBTA_LEGACY = {')
    for (const name of legacyNames) {
      const replacement = tokens.deprecations?.[`lbta-${name}`]
      if (replacement) {
        lines.push(`  /** @deprecated Use ${replacement} instead. */`)
      }
      lines.push(`  ${kebabToCamel(name)}: '${tokens.colors.lbta[name]}',`)
    }
    lines.push('} as const')
    lines.push('')
  }

  // Combined LBTA — kept for backwards compat (existing imports)
  lines.push('/**')
  lines.push(' * Combined lbta.* palette (utility + legacy). Kept for backwards compat with existing imports.')
  lines.push(' * New code should prefer LBTA_UTIL (allowed) or BRAND (brand identity).')
  lines.push(' */')
  lines.push('export const LBTA = {')
  for (const [token, value] of Object.entries(tokens.colors.lbta)) {
    lines.push(`  ${kebabToCamel(token)}: '${value}',`)
  }
  lines.push('} as const')
  lines.push('')

  // Deprecations map — used by check-brand-usage.ts
  if (tokens.deprecations) {
    lines.push('/**')
    lines.push(' * Deprecated Tailwind class names → recommended replacements.')
    lines.push(' * Used by scripts/check-brand-usage.ts to enforce migration.')
    lines.push(' * Single source: `tokens/lbta-web-tokens.json` `deprecations` field.')
    lines.push(' */')
    lines.push('export const DEPRECATED_LBTA_CLASSES: Readonly<Record<string, string>> = {')
    for (const [from, to] of Object.entries(tokens.deprecations)) {
      lines.push(`  '${from}': '${to}',`)
    }
    lines.push('} as const')
    lines.push('')
  }

  return lines.join('\n')
}

async function main() {
  const raw = await readFile(tokenFilePath, 'utf8')
  const parsed = JSON.parse(raw) as TokenFile

  const tailwindPayload = {
    brand: parsed.colors.brand,
    lbta: parsed.colors.lbta,
  }

  const tailwindJson = `${JSON.stringify(tailwindPayload, null, 2)}\n`
  const cssVars = buildCssVariables(parsed)
  const typedTs = buildTypedTokens(parsed)

  await mkdir(generatedDir, { recursive: true })
  await mkdir(libDir, { recursive: true })
  await writeFile(tailwindOutputPath, tailwindJson, 'utf8')
  await writeFile(cssOutputPath, cssVars, 'utf8')
  await writeFile(tsOutputPath, typedTs, 'utf8')

  console.log(`Generated ${path.relative(repoRoot, tailwindOutputPath)}`)
  console.log(`Generated ${path.relative(repoRoot, cssOutputPath)}`)
  console.log(`Generated ${path.relative(repoRoot, tsOutputPath)}`)
}

main().catch((error) => {
  console.error('Failed to build tokens.')
  console.error(error)
  process.exitCode = 1
})
