/**
 * sot-seed.cjs — Project Operating Kit: Supabase SoT table seeder
 * Project: lbta-website-draft-3-5-26
 * Generated by project-kit-apply.sh on 2026-06-22
 *
 * MANUAL STEP — do NOT run automatically. Run once when ready:
 *   POSTGRES_URL="postgres://..." node scripts/sot-seed.cjs
 *
 * Idempotent: safe to re-run; uses CREATE TABLE IF NOT EXISTS + ON CONFLICT DO NOTHING.
 * Does NOT touch any existing project data.
 */

'use strict';

const { Client } = require('pg');

const SLUG = 'lbta-website-draft-3-5-26';

async function seed() {
  const url = process.env.POSTGRES_URL;
  if (!url) {
    console.error('ERROR: POSTGRES_URL environment variable is not set.');
    console.error('Run: POSTGRES_URL="postgres://..." node scripts/sot-seed.cjs');
    process.exit(1);
  }

  const client = new Client({ connectionString: url, ssl: { rejectUnauthorized: false } });
  await client.connect();
  console.log(`[sot-seed] Connected. Seeding SoT tables for project: ${SLUG}`);

  try {
    // -- work_items: the live plan rows --
    await client.query(`
      CREATE TABLE IF NOT EXISTS ${SLUG}_work_items (
        id            TEXT PRIMARY KEY,
        title         TEXT NOT NULL,
        description   TEXT,
        status        TEXT NOT NULL DEFAULT 'todo'
                          CHECK (status IN ('todo','in_progress','blocked','done')),
        priority      INTEGER NOT NULL DEFAULT 50,
        sort_order    INTEGER,
        owner         TEXT,
        next_action   TEXT,
        blocked_by    TEXT,
        lane          TEXT,
        created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        updated_at    TIMESTAMPTZ NOT NULL DEFAULT NOW()
      );
    `);
    console.log(`  [ok] ${SLUG}_work_items`);

    // -- build_queue: phased build steps --
    await client.query(`
      CREATE TABLE IF NOT EXISTS ${SLUG}_build_queue (
        id            TEXT PRIMARY KEY,
        phase         TEXT NOT NULL,
        step          TEXT NOT NULL,
        status        TEXT NOT NULL DEFAULT 'todo'
                          CHECK (status IN ('todo','in_progress','done','skipped')),
        lane          TEXT,
        depends_on    TEXT,
        notes         TEXT,
        created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        updated_at    TIMESTAMPTZ NOT NULL DEFAULT NOW()
      );
    `);
    console.log(`  [ok] ${SLUG}_build_queue`);

    // -- decisions: gated/decided calls --
    await client.query(`
      CREATE TABLE IF NOT EXISTS ${SLUG}_decisions (
        id            TEXT PRIMARY KEY,
        title         TEXT NOT NULL,
        decision      TEXT NOT NULL,
        rationale     TEXT,
        decided_by    TEXT NOT NULL DEFAULT 'drew',
        decided_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        reversible    BOOLEAN NOT NULL DEFAULT TRUE,
        status        TEXT NOT NULL DEFAULT 'active'
                          CHECK (status IN ('active','superseded','rolled_back'))
      );
    `);
    console.log(`  [ok] ${SLUG}_decisions`);

    // -- source_index: pointers to every canonical doc/repo/folder --
    await client.query(`
      CREATE TABLE IF NOT EXISTS ${SLUG}_source_index (
        id            TEXT PRIMARY KEY,
        label         TEXT NOT NULL,
        kind          TEXT NOT NULL CHECK (kind IN ('file','dir','url','supabase_table','skill','tool')),
        pointer       TEXT NOT NULL,
        notes         TEXT,
        updated_at    TIMESTAMPTZ NOT NULL DEFAULT NOW()
      );
    `);
    console.log(`  [ok] ${SLUG}_source_index`);

    // Seed the source_index with the kit's own pointers (idempotent via ON CONFLICT DO NOTHING)
    await client.query(`
      INSERT INTO ${SLUG}_source_index (id, label, kind, pointer, notes)
      VALUES
        ('sot-doc',    'Source of truth doc',  'file',            'docs/PROJECT_SOURCE_OF_TRUTH.md', 'Human+agent handoff'),
        ('lane-map',   'Build lanes map',       'file',            'docs/BUILD_LANES.md',             'Disjoint owner areas'),
        ('ci',         'GitHub Actions CI',     'file',            '.github/workflows/ci.yml',        'Advisory → required'),
        ('sot-mirror', 'SoT JSON mirror',       'dir',             'docs/source-of-truth/',           'Auto-refreshed on commit'),
        ('work-items', 'Work items table',      'supabase_table',  '${SLUG}_work_items',              'Live plan rows'),
        ('build-q',    'Build queue table',     'supabase_table',  '${SLUG}_build_queue',             'Phased steps'),
        ('decisions',  'Decisions table',       'supabase_table',  '${SLUG}_decisions',               'Gated calls'),
        ('src-index',  'Source index table',    'supabase_table',  '${SLUG}_source_index',            'Canonical pointers')
      ON CONFLICT (id) DO NOTHING;
    `);
    console.log(`  [ok] ${SLUG}_source_index seeded with kit pointers`);

    console.log(`\n[sot-seed] Done. Tables ready for project: ${SLUG}`);
    console.log(`\nNext: populate work items from your slice list, then run:\n  node scripts/sot.cjs\n`);
  } finally {
    await client.end();
  }
}

seed().catch(err => {
  console.error('[sot-seed] FAILED:', err.message);
  process.exit(1);
});
