import Link from 'next/link'
import type {
  LessonPlan,
  LessonPlanDraft,
  ProgramFamily,
} from '@/lib/lesson-plan-types'
import { PROGRAM_FAMILIES } from '@/lib/lesson-plan-types'
import LessonPlanCard from './LessonPlanCard'

interface Props {
  allPlans: LessonPlan[]
  /** Optional generated drafts shown after curated grid (filter applies to these too) */
  drafts?: LessonPlanDraft[]
  /** Active filter from query string, or null = "all" */
  activeProgram: ProgramFamily | null
  /** All program families that have at least one plan (for filter chips) */
  activeFamilies: ProgramFamily[]
  coachSlug: string
}

export default function LessonPlanLibraryView({
  allPlans,
  drafts = [],
  activeProgram,
  activeFamilies,
  coachSlug,
}: Props) {
  const filteredCurated = activeProgram
    ? allPlans.filter((p) => p.program === activeProgram)
    : allPlans

  const filteredDrafts = activeProgram
    ? drafts.filter((d) => d.program === activeProgram)
    : drafts

  const filterChips = PROGRAM_FAMILIES.filter((f) =>
    activeFamilies.includes(f.id)
  )

  const totalShowing = filteredCurated.length + filteredDrafts.length

  return (
    <div className="max-w-[1100px] mx-auto px-4 sm:px-6 py-6 pb-24">
      <Header
        coachSlug={coachSlug}
        totalCurated={allPlans.length}
        totalDrafts={drafts.length}
        showingCount={totalShowing}
        activeProgram={activeProgram}
      />

      <FilterChips
        chips={filterChips}
        activeProgram={activeProgram}
        coachSlug={coachSlug}
      />

      {totalShowing === 0 ? (
        <EmptyFilterState coachSlug={coachSlug} />
      ) : (
        <>
          {filteredCurated.length > 0 ? (
            <ul className="grid gap-4 grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 mt-6 list-none p-0">
              {filteredCurated.map((plan) => (
                <li key={plan.id}>
                  <LessonPlanCard plan={plan} coachSlug={coachSlug} />
                </li>
              ))}
            </ul>
          ) : null}

          {filteredDrafts.length > 0 ? (
            <DraftsSection
              drafts={filteredDrafts}
              coachSlug={coachSlug}
            />
          ) : null}
        </>
      )}
    </div>
  )
}

function DraftsSection({
  drafts,
  coachSlug,
}: {
  drafts: LessonPlanDraft[]
  coachSlug: string
}) {
  return (
    <section className="mt-12">
      <header className="pb-3 mb-5 border-b border-black/8">
        <p className="font-sans text-eyebrow text-brand-victoria-cove mb-2">
          Generated drafts
        </p>
        <p className="text-sm text-brand-pacific-dusk/75">
          Plans composed by coaches from the LBTA framework. Click into any
          draft for the full breakdown.
        </p>
      </header>
      <ul className="grid gap-4 grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 list-none p-0">
        {drafts.map((draft) => (
          <li key={draft.id}>
            <DraftCard draft={draft} coachSlug={coachSlug} />
          </li>
        ))}
      </ul>
    </section>
  )
}

function DraftCard({
  draft,
  coachSlug,
}: {
  draft: LessonPlanDraft
  coachSlug: string
}) {
  const meta = PROGRAM_FAMILIES.find((f) => f.id === draft.program)
  return (
    <Link
      href={`/coach-hub/${coachSlug}/lesson-plans/drafts/${draft.id}`}
      className="group block bg-brand-sandstone/40 rounded-[14px] border border-black/8 border-l-4 border-l-brand-pacific-dusk/40 p-5 shadow-[0_1px_0_rgba(27,58,92,0.04)] transition-all duration-200 hover:border-black/15 hover:-translate-y-0.5 hover:shadow-[0_1px_0_rgba(27,58,92,0.04),0_8px_24px_-8px_rgba(27,58,92,0.10)] focus:outline-none focus:ring-2 focus:ring-brand-victoria-cove focus:ring-offset-2"
    >
      <div className="flex items-baseline justify-between gap-3 mb-2">
        <span className="font-sans text-eyebrow-sm text-brand-pacific-dusk/70">
          Draft
          <span className="text-brand-pacific-dusk/40 ml-1.5 normal-case tracking-normal">
            · {meta?.label ?? draft.program}
          </span>
        </span>
        <span className="font-sans text-[11px] text-brand-pacific-dusk/55 font-medium tabular-nums whitespace-nowrap">
          {draft.durationMin} min
        </span>
      </div>
      <h3 className="font-headline font-normal text-[20px] leading-tight text-brand-deep-water tracking-[-0.01em] mb-2 group-hover:text-brand-pacific-dusk transition-colors">
        {draft.title}
      </h3>
      <p className="text-sm text-brand-pacific-dusk/75 leading-snug mb-3">
        {draft.focus}
      </p>
      <p className="font-sans text-[11px] text-brand-pacific-dusk/55">
        Generated by {draft._meta.generatedBy} ·{' '}
        {new Date(draft._meta.createdAt).toLocaleDateString(undefined, {
          month: 'short',
          day: 'numeric',
        })}
      </p>
    </Link>
  )
}

function Header({
  coachSlug,
  totalCurated,
  totalDrafts,
  showingCount,
  activeProgram,
}: {
  coachSlug: string
  totalCurated: number
  totalDrafts: number
  showingCount: number
  activeProgram: ProgramFamily | null
}) {
  const totalLibrary = totalCurated + totalDrafts
  return (
    <header className="pt-4 pb-6 mb-2 border-b border-black/8">
      <p className="font-sans text-eyebrow text-brand-victoria-cove mb-3">
        Lesson plan library
      </p>
      <h1 className="font-headline font-light text-brand-deep-water leading-[1.05] tracking-[-0.02em] text-[clamp(28px,6vw,42px)] mb-3">
        Pick a plan, then teach it.
      </h1>
      <p className="text-sm text-brand-pacific-dusk/75 mb-4 max-w-[640px] leading-relaxed">
        {totalCurated} canonical plans built on the LBTA 4-block schema
        {totalDrafts > 0 ? ` + ${totalDrafts} generated draft${totalDrafts === 1 ? '' : 's'}` : ''}.
        Filter by program below, then click a card to see the full breakdown.
      </p>
      <div className="flex flex-wrap items-center gap-3 text-sm mb-4">
        <span className="text-brand-pacific-dusk/65">
          {activeProgram ? (
            <>
              Showing <strong className="text-brand-deep-water font-semibold">{showingCount}</strong> of{' '}
              <strong className="text-brand-deep-water font-semibold">{totalLibrary}</strong>
            </>
          ) : (
            <>
              Showing all <strong className="text-brand-deep-water font-semibold">{totalLibrary}</strong>
            </>
          )}
        </span>
        <span className="text-brand-pacific-dusk/30">·</span>
        <Link
          href={`/coach-hub/${coachSlug}/lesson-plans/framework`}
          className="font-sans text-sm font-medium text-brand-victoria-cove hover:text-brand-pacific-dusk transition-colors focus:outline-none focus:ring-2 focus:ring-brand-victoria-cove focus:ring-offset-2 rounded-sm"
        >
          View the 4-block framework →
        </Link>
      </div>
      <Link
        href={`/coach-hub/${coachSlug}/lesson-plans/generate`}
        className="inline-flex items-center justify-center bg-brand-deep-water text-white font-sans text-sm font-medium tracking-[2px] uppercase min-h-[48px] px-6 py-3 rounded-[2px] transition-all duration-300 ease-out hover:bg-brand-pacific-dusk hover:-translate-y-0.5 focus:outline-none focus:ring-2 focus:ring-brand-victoria-cove focus:ring-offset-2"
      >
        Generate a new plan
      </Link>
    </header>
  )
}

function FilterChips({
  chips,
  activeProgram,
  coachSlug,
}: {
  chips: typeof PROGRAM_FAMILIES
  activeProgram: ProgramFamily | null
  coachSlug: string
}) {
  return (
    <nav
      aria-label="Filter plans by program"
      className="flex gap-2 overflow-x-auto py-3 -mx-1 px-1"
    >
      <FilterChip
        href={`/coach-hub/${coachSlug}/lesson-plans`}
        label="All programs"
        active={activeProgram === null}
      />
      {chips.map((chip) => (
        <FilterChip
          key={chip.id}
          href={`/coach-hub/${coachSlug}/lesson-plans?program=${chip.id}`}
          label={chip.label}
          active={activeProgram === chip.id}
        />
      ))}
    </nav>
  )
}

function FilterChip({
  href,
  label,
  active,
}: {
  href: string
  label: string
  active: boolean
}) {
  return (
    <Link
      href={href}
      className={[
        'inline-flex items-center px-4 py-2 min-h-[40px] rounded-full text-sm font-sans font-medium whitespace-nowrap',
        'transition-all focus:outline-none focus:ring-2 focus:ring-brand-victoria-cove focus:ring-offset-2',
        active
          ? 'bg-brand-deep-water text-white hover:bg-brand-pacific-dusk'
          : 'bg-white border border-black/10 text-brand-pacific-dusk hover:border-brand-victoria-cove/40 hover:text-brand-deep-water',
      ].join(' ')}
      aria-pressed={active}
    >
      {label}
    </Link>
  )
}

function EmptyFilterState({ coachSlug }: { coachSlug: string }) {
  return (
    <div className="mt-12 text-center">
      <p className="font-headline text-xl text-brand-deep-water mb-2">
        No plans match this filter.
      </p>
      <p className="text-sm text-brand-pacific-dusk/70 mb-4">
        Try a different program — or view all.
      </p>
      <Link
        href={`/coach-hub/${coachSlug}/lesson-plans`}
        className="inline-flex items-center px-5 py-2.5 min-h-[44px] bg-brand-deep-water text-white text-sm font-sans font-medium rounded-full hover:bg-brand-pacific-dusk transition-colors focus:outline-none focus:ring-2 focus:ring-brand-victoria-cove focus:ring-offset-2"
      >
        Show all plans
      </Link>
    </div>
  )
}
